
const {ccclass, property, requireComponent} = cc._decorator;

@ccclass
export default class NewClass extends cc.Component {
    start () {
        window.initMgr();
        cc.fx.GameConfig.init();
        // cc.fx.AudioManager._instance.init();
    }

    //开始游戏，跳转至引导页面
    startGame(){
        cc.director.loadScene("GuideScene");
    }
    //备用，用来测试跳转 指定关卡
    clickBtn(event,data){
        cc.fx.GameConfig.GM_INFO.custom = parseInt(data);
        cc.director.loadScene("GameScene");
    }   
    //打开排行榜
    openRank(){
        cc.director.loadScene("RankScene");
    }
    
    protected update(dt: number): void {
    }
}
